import LeftSidebar from "@/components/shared/LeftSidebar";
import { BLOG_POSTS_DIR } from "@/components/posts/config";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const blogContainerStyle = {
  boxSizing:"Border-box",
  width:"40%",
  minWidth:"50rem",
};

export default function BlogLayout({ children }) {
  return <>
    <LeftSidebar postsDir={BLOG_POSTS_DIR} />
    <div style={blogContainerStyle}>{children}</div>;
  </>
}